[flipside]
# input your Flipside API key here
api_key = "FLIPSIDE_KEY_HERE"

[helius]
# input your Helius API key here
api_key = "HELIUS_KEY_HERE"

[hide_pages]
# list of pages to hide from the sitemap
pages_to_hide = [] 